### ISSUE TITLE
HGamer3D-Data-0.5.0 does not compile with GHC 7.10.1

### ISSUE THREAD

**Issue by peti** [urs-of-the-backwoods/HGamer3D#7]
Citing from http://hydra.cryp.to/build/778446/log/raw:

    HGamer3D/Data/GameTime.hs:61:10:
        Duplicate instance declarations:
          instance Num GameTime -- Defined at HGamer3D/Data/GameTime.hs:61:10
          instance Num C.TimeSpec -- Defined in ‘System.Clock’

**Comment by urs-of-the-backwoods** [comment]
Hi Peter,

thanks for notification. I'm currently working on a major re-write and
simplification of HGamer3D for version 0.6. It looks promising but since it
is a Hobby project, I cannot predict when it will be ready.

best regards
Peter (aka uotbw)

2015-04-20 22:42 GMT+02:00 Peter Simons <notifications@github.com>:

**Comment by peti** [comment]
Okay. In that case I'll remove the HGamer packages from the NixOS distribution for the time being.

**Comment by deepfire** [comment]
Hi!  Was 69cacdb535 supposed to make HGamer3D compile in GHC 7.10?

**Comment by urs-of-the-backwoods** [comment]
Hi deepfire,

no 69cacdb is a different branch for version 0.6 and as written above, there are different plans for this version. Sorry for bad news, but new version will be exciting, it is just not ready for now to publish.

regards uotbw

**Comment by urs-of-the-backwoods** [comment]
Hi deepfire,

with new version 0.7 installation should be easier on linux, you might retest on Nix os (although it might be that binary install scheme is not what you are thinking of?).
