### ISSUE TITLE
cabal install fails

### ISSUE THREAD

**Issue by vladfi1** [urs-of-the-backwoods/HGamer3D#8]
```cabal install HGamer3D``` fails with ```* Missing C libraries: hgamer3d062, Urho3D```

**Comment by vladfi1** [comment]
I followed the linux build instructions at http://www.hgamer3d.org/Install.html#linux which appeared to finish successfully. Afterwards I was not able to import any HGamer3D modules in ghci, but it did appear that as a side effect the missing C libraries were built. I then tried ```cabal install HGamer3D --extra-lib-dirs=/usr/local/lib/Urho3D/```, which succeeded, and I can now use HGamer3D in ghci.

**Comment by urs-of-the-backwoods** [comment]
Hi Vlad, happy to see that you finally succeeded. I think the issue is due to the fact that the Python build script behind the scenes uses the stack Haskell toolchain and in this GHCI needs to be called with stack exec ghci -- <parameters>, then it should find its libraries. Since I wrapped the build-steps with a python script, this is not immediately obvious. I will investigate this a little bit. Which linux are you using?
regards
uotbw

**Comment by vladfi1** [comment]
Ah so stack is installing to its own sandbox, but the C libraries are installed system-wide. I think it is a bit weird to be using the python build scripts for a Haskell project - I would expect to be able to do the same thing with just cabal (or stack).

**Comment by urs-of-the-backwoods** [comment]
obsolete due to new version 0.7, which uses different scheme.
